### ISSUE TITLE
[BUG] Game is Queued and File size is N/A

### ISSUE THREAD

**Issue by vlldzlv** [hydralauncher/hydra#694]
### Describe the bug

Wanted to download the game, synced the sources, choosed the folder and after that game just not downloading
![Снимок экрана 2024-06-26 140635](https://github.com/hydralauncher/hydra/assets/161371406/32a98362-9bdf-4707-815d-0d49360fa133)

### Steps to Reproduce

what i need to do?

### Expected behavior

/

### Screenshots

![Снимок экрана 2024-06-26 140635](https://github.com/hydralauncher/hydra/assets/161371406/d45ae27c-a901-4d29-836f-25409dec8500)

### Operating System

Windows 11

### Hydra Version

v. 2.0.1.

**Comment by unqxl** [comment]
+1

I also have the same problem. 
After selecting the repacker game is added to downloads, and then goes forever "getting metadata"

**Comment by zamitto** [comment]
@unqxl @vlldzlv could you test it again in 2.0.2? Should be fixed

**Comment by unqxl** [comment]
@zamitto yes, the problem is solved, thanks 👍

**Comment by nauxnam** [comment]
Well... this problem still exists.. Hydra version 2.1.7
![image](https://github.com/user-attachments/assets/11b9923d-bbc3-4e4d-9b82-88b348a81907)
